---
- hosts: all
  sudo: yes
  tasks:
  - name: Create a stld user
    user: name=stld state=present shell=/bin/bash createhome=yes
  - name: Install coffeescript
    apt: update_cache=yes pkg=coffeescript state=latest

- include: playbooks/postgres/setup_db.yml

- include: playbooks/ruby/install.yml

- include: playbooks/nginx/setup.yml

- include: playbooks/deployment/prepare.yml

- include: playbooks/upstart/configure.yml
