---
- hosts: all
  name: create a stld user
  sudo: yes
  tasks:
  - user: name=stld state=present shell=/bin/bash createhome=yes

- include: playbooks/ruby/install.yml

- include: playbooks/postgres/setup_db.yml

- include: playbooks/deployment/prepare.yml
