---
- name: Link database.yml
  file: path={{ current_config }}/database.yml state=link
        src="{{ shared_config }}/database.yml"

- name: Link unicorn.rb
  file: path="{{ current_config }}/unicorn.rb" state=link
        src="{{ shared_config }}/unicorn.rb"

- name: Link log directory
  file: path="{{ app_root }}/current/log"
        state=link
        src=/var/log/{{stld_user}}
