---
- name: update bundle
  shell: bundle --path ../shared/vendor/bundle
         chdir="{{ current_dir }}"

- name: Run sequel migrations
  shell: RACK_ENV={{rack_env}} bundle exec ruby script/migrate.rb
         chdir="{{ current_dir }}"

- name: Make
  shell: make
         chdir="{{ current_dir }}"
