---
# Create a Capistrano-like structure

- hosts: all
  sudo_user: stld
  sudo: yes
  tasks:
  - name: Create a timestamp
    command: "date +%s"
    register: timestamp

  - name: Pull from git
    git: repo=https://github.com/ostapneko/stld
         dest=/home/${stld_user}/apps/stld/releases/${timestamp.stdout}

  - name: Destroy link to previous release
    file: path=/home/${stld_user}/apps/stld/current state=absent

  - name: Link to current release
    file: path=/home/${stld_user}/apps/stld/current state=link
          src=/home/${stld_user}/apps/stld/releases/${timestamp.stdout}

  - include: tasks/links.yml

  - include: tasks/update_app.yml

- hosts: all
  sudo: yes
  tasks:
  - name: Get unicorn PID
    command: cat /home/${stld_user}/apps/stld/shared/pids/unicorn.pid
    register: unicorn_pid
    ignore_errors: true
  - name: start unicorn
    command: /sbin/start stld
    when: unicorn_pid|failed
  - name: Kill unicorn
    command: kill {{ unicorn_pid.stdout }}
    when: unicorn_pid|success
