---
# Create a Capistrano-like structure

- hosts: all
  sudo_user: stld
  sudo: yes
  tasks:
  - name: Create a timestamp
    command: "date +%s"
    register: timestamp

  - name: Pull from git
    git: repo=https://github.com/ostapneko/stld
         dest=${app_root}/releases/${timestamp.stdout}

  - name: Destroy link to previous release
    file: path=$app_root/current state=absent

  - name: Link to current release
    file: path=${app_root}/current state=link
          src=${app_root}/releases/${timestamp.stdout}

  - name: Link database.yml
    file: path=${app_root}/current/config/database.yml state=link
          src=${app_root}/shared/config/database.yml

  - name: Link unicorn.rb
    file: path=${app_root}/current/config/unicorn.rb state=link
          src=${app_root}/shared/config/unicorn.rb

  - name: update bundle
    shell: bundle
           chdir=${app_root}/current
    environment: $ruby_env

  - name: Run sequel migrations
    shell: bundle exec ruby script/migrate.rb
           chdir=${app_root}/current
    environment: $ruby_env

  - name: Compile assets
    shell: /usr/bin/coffee --compile --output public/js public/coffee
           chdir=${app_root}/current

  #- name: Restart unicorn
