---
# Prepare Capistrano-like file structure
- hosts: all
  sudo_user: ${stld_user}
  sudo: yes
  tasks:
  - name: Create a releases directory
    file: path=/home/${stld_user}/apps/{{stld_user}}/releases
          state=directory

  - name: Create a shared config directory
    file: path=/home/${stld_user}/apps/{{stld_user}}/shared/config
          state=directory

  - name: Create a shared pids directory
    file: path=/home/${stld_user}/apps/{{stld_user}}/shared/pids
          state=directory

  - name: Copy database.yml
    template: src=../../files/approot/config/database.yml.j2
              dest=/home/${stld_user}/apps/{{stld_user}}/shared/config/database.yml

  - name: Copy unicorn.rb
    template: src=../../files/approot/config/unicorn.rb.j2
              dest=/home/${stld_user}/apps/{{stld_user}}/shared/config/unicorn.rb

  - name: Create a log directory
    sudo_user: root
    file: path=/var/log/{{stld_user}}
          state=directory
          owner={{stld_user}}
          group={{stld_user}}

- hosts: development
  sudo: yes
  sudo_user: ${stld_user}
  tasks:
  - name: Pull from git
    git: repo=https://github.com/ostapneko/{{stld_user}}
         dest=/home/${stld_user}/apps/{{stld_user}}/workspace

  - name: Link to current release
    file: path=/home/${stld_user}/apps/{{stld_user}}/current state=link
          src=/home/${stld_user}/apps/{{stld_user}}/workspace

  - include: tasks/links.yml

  - include: tasks/update_app.yml

  - name: Run sequel migrations
    shell: RACK_ENV=test bundle exec ruby script/migrate.rb
           chdir=/home/${stld_user}/apps/{{stld_user}}/current
