---
# Prepare Capistrano-like file structure
- hosts: all
  sudo_user: stld
  sudo: yes
  tasks:
  - name: Create a releases directory
    file: path=${app_root}/releases
          state=directory

  - name: Create a shared directory
    file: path=${app_root}/shared/config
          state=directory

  - name: Copy database.yml
    copy: src=../../files/database.yml
          dest=${app_root}/shared/config/database.yml

  - name: Copy unicorn.rb
    copy: src=../../files/unicorn.rb
          dest=${app_root}/shared/config/unicorn.rb
