---
# Prepare Capistrano-like file structure
- hosts: all
  sudo_user: "{{ stld_user }}"
  sudo: yes
  vars:
    - shared_config: "{{ app_root }}/shared/config"
  tasks:
  - name: Create the app root
    file: path="{{app_root}}"
          state=directory

  - name: Create a releases directory
    file: path="{{ app_root }}/releases"
          state=directory

  - name: Create a shared config directory
    file: path="{{ shared_config }}"
          state=directory

  - name: Create a shared pids directory
    file: path="{{ app_root }}/shared/pids"
          state=directory

  - name: Copy database.yml
    template: src=../../files/approot/config/database.yml.j2
              dest="{{ shared_config }}/database.yml"

  - name: Copy unicorn.rb
    template: src=../../files/approot/config/unicorn.rb.j2
              dest="{{ shared_config }}/unicorn.rb"

  - name: Create a log directory
    sudo_user: root
    file: path=/var/log/{{ stld_user }}
          state=directory
          owner={{ stld_user }}
          group={{ stld_user }}
