- name: checkout rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git
       dest={{ ruby_env["RBENV_ROOT"] }}

- name: checkout ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest={{ ruby_env["RBENV_ROOT"] }}/plugins/ruby-build

- name: check ruby presence
  shell: ruby -v | grep ${ruby_version}
  register: ruby_present
  ignore_errors: yes
  environment: ruby_env

- name: install ruby {{ ruby_env["RBENV_VERSION"] }}
  shell: rbenv install {{ ruby_env["RBENV_VERSION"] }}
  when_failed: $ruby_present
  environment: ruby_env

- name: rbenv rehash
  shell: rbenv rehash
  environment: ruby_env

- name: check bundler presence
  shell: bundle -v
  register: bundler_present
  ignore_errors: true
  environment: ruby_env

- name: install bundler
  shell: gem install bundler && rbenv rehash
  when_failed: $bundler_present
  environment: ruby_env
