- name: checkout rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git
       dest={{ ruby_env["RBENV_ROOT"] }}

- name: checkout ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest={{ ruby_env["RBENV_ROOT"] }}/plugins/ruby-build

- name: check ruby presence
  shell: cd; ruby -v | grep {{ ruby_env["RUBY_VERSION"] }}
  register: ruby_present
  ignore_errors: yes
  environment: ruby_env

- name: install ruby
  shell: rbenv install {{ ruby_env["RBENV_VERSION"] }}
         chdir=/home/stld
  when: ruby_present|failed
  environment: ruby_env

- name: rbenv rehash
  shell: rbenv rehash
         chdir=/home/stld
  environment: ruby_env

- name: check bundler presence
  shell: bundle -v
         chdir=/home/stld
  register: bundler_present
  ignore_errors: true
  environment: ruby_env

- name: install bundler
  shell: gem install bundler && rbenv rehash
         chdir=/home/stld
  when: bundler_present|failed
  environment: ruby_env
