- hosts: all
  sudo: yes
  tasks:
  - name: Install Nginx
    apt: update_cache=yes pkg=nginx state=latest

  - name: Copy stld conf file
    copy: src=../../files/etc/nginx/sites-available/stld.conf
          dest=/etc/nginx/sites-available/stld.conf

  - name: enable stld
    file: path=/etc/nginx/sites-enabled/stld.conf
          src=/etc/nginx/sites-available/stld.conf
          state=link
