---
- name: install CRuby dependencies
  sudo: yes
  apt: update_cache=yes pkg=$item state=latest
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - git-core
    - libc6-dev
    - libffi-dev
    - libgdbm-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libyaml-dev
    - openssl
    - pkg-config
    - zlib1g
    - zlib1g-dev
